# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from csvq import *
import pyqtgraph as pg
from PyQt5.QtWidgets import QMessageBox, QFileDialog, QWidget
from PyQt5.QtCore import *
import os
import config
from csvq import GetDate
import numpy as np

counry_select = ""
region_select = ""
station_select = ""

path = ''

class Selected_files(object):
    filename_temp_1 = ""
    filename_srznach_2 = ""
    filename_max_3 = ""

    def set_filename_1(self, file_new):
        self.filename_temp_1 = file_new

    def set_filename_srznach_2(self, file_new1):
        self.filename_srznach_2 = file_new1

    def set_filename_max_3(self, file_new2):
        self.filename_max_3 = file_new2


class Ui_widget_select_files(object):
    def file_1_temp_open(self):
        pwd_ = os.getcwd()
        filename, _ = QFileDialog.getOpenFileName(None, "Open File", ".", "Comma-Separated Values (*.csv);")
        # res = QFileDialog.getOpenFileName(self, 'open File', 'C:\\')
        if filename != "":
            self.label_temp_widget_1_path.setText("Path: " + filename)

    def file_2_srznash_open(self):
        pwd_ = os.getcwd()
        filename, _ = QFileDialog.getOpenFileName(None, "Open File", ".", "Comma-Separated Values (*.csv);")
        # res = QFileDialog.getOpenFileName(self, 'open File', 'C:\\')
        if filename != "":
            self.label_srznash_widget_path_2.setText("Path: " + filename)

    def file_3_max_open(self):
        pwd_ = os.getcwd()
        filename, _ = QFileDialog.getOpenFileName(None, "Open File", ".", "Comma-Separated Values (*.csv);")
        # res = QFileDialog.getOpenFileName(self, 'open File', 'C:\\')
        if filename != "":
            self.label_widget_path_3.setText("Path: " + filename)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_max_widget_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_max_widget_3.setGeometry(QtCore.QRect(10, 240, 791, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_max_widget_3.setFont(font)
        self.label_max_widget_3.setObjectName("label_max_widget_3")
        self.label_widget_path_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_widget_path_3.setGeometry(QtCore.QRect(10, 290, 411, 16))
        self.label_widget_path_3.setObjectName("label_widget_path_3")
        self.label_temp_widget_1_path = QtWidgets.QLabel(self.centralwidget)
        self.label_temp_widget_1_path.setGeometry(QtCore.QRect(10, 50, 791, 16))
        self.label_temp_widget_1_path.setObjectName("label_temp_widget_1_path")
        self.label_srznash_widget_path_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_srznash_widget_path_2.setGeometry(QtCore.QRect(10, 160, 411, 16))
        self.label_srznash_widget_path_2.setObjectName("label_srznash_widget_path_2")
        self.label_srznash_widget_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_srznash_widget_2.setGeometry(QtCore.QRect(10, 110, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_srznash_widget_2.setFont(font)
        self.label_srznash_widget_2.setObjectName("label_srznash_widget_2")
        self.label_temp_widget = QtWidgets.QLabel(self.centralwidget)
        self.label_temp_widget.setGeometry(QtCore.QRect(10, 10, 781, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_temp_widget.setFont(font)
        self.label_temp_widget.setObjectName("label_temp_widget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(810, 10, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(810, 120, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 250, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 340, 191, 31))
        self.pushButton_4.setStyleSheet("font-size: 14px")
        self.pushButton_4.setObjectName("pushButton_4")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_max_widget_3.setText(_translate("MainWindow", "Файл с максимальными суммамми выпавших осадков"))
        self.label_widget_path_3.setText(_translate("MainWindow", "Path: "))
        self.label_temp_widget_1_path.setText(_translate("MainWindow", "Path: "))
        self.label_srznash_widget_path_2.setText(_translate("MainWindow", "Path: "))
        self.label_srznash_widget_2.setText(_translate("MainWindow", "Файл месячных и годовых сумм выпавших осадков"))
        self.label_temp_widget.setText(_translate("MainWindow", "Файл с температурой"))
        self.pushButton.setText(_translate("MainWindow", "Выберете файл"))
        self.pushButton_2.setText(_translate("MainWindow", "Выберете файл"))
        self.pushButton_3.setText(_translate("MainWindow", "Выберете файл"))
        self.pushButton_4.setText(_translate("MainWindow", "Открыть "))

        self.pushButton.clicked.connect(self.file_1_temp_open)
        self.pushButton_2.clicked.connect(self.file_2_srznash_open)
        self.pushButton_3.clicked.connect(self.file_3_max_open)





class Ui_MainWindow(object):

    def update_cb2_cb3(self, dict_combo):
        # print(123)
        # dict_combo=first_config("monthly_and_annual_precipitation_amounts.csv")

        value = self.comboBox.currentText()
        self.comboBox_2.clear()
        self.comboBox_2.addItems(dict_combo[self.comboBox.currentText()])

    def update_cb3(self, dict_combo):
        # print("12334")
        # print(dict_combo[self.comboBox.currentText()])
        value = self.comboBox_2.currentText()
        self.comboBox_3.clear()
        if ((dict_combo[self.comboBox.currentText()] != '') and (self.comboBox_2.currentText() != '')):
            self.comboBox_3.addItems(dict_combo[self.comboBox.currentText()][self.comboBox_2.currentText()])

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-100, -120, 1061, 551))
        self.label_4.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.017, y1:1, x2:1, y2:0.029, stop:0 rgba(214, 19, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "background-color: qlineargradient(spread:pad, x1:0.017, y1:1, x2:1, y2:0, stop:0 rgba(211, 0, 255, 255), stop:1 rgba(113, 117, 255, 255));")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 10, 81, 19))
        self.label_3.setStyleSheet("font-size: 16px;\n"
                                   "color: #fff;\n"
                                   "font: 75 16pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(570, 40, 262, 34))
        self.comboBox_3.setStyleSheet("#comboBox_3{\n"
                                      "font: 75 10pt \"Arial\";\n"
                                      "color: #fff;\n"
                                      "border-radius: 8px;\n"
                                      "border: 1px solid #FFF;\n"
                                      "background: rgba(217, 217, 217, 0.10);\n"
                                      "}\n"
                                      "#comboBox_3::drop-down{\n"
                                      "border: 0px;\n"
                                      "}\n"
                                      "#comboBox_3::down-arrow{\n"
                                      "image: url(./newPrefix/arrow_drop_down_icon_206159.svg);\n"
                                      "margin-right: 15px;\n"
                                      "}\n"
                                      "#comboBox_3::one{\n"
                                      "border: 1px solid #FFF;\n"
                                      "}\n"
                                      "#comboBox_3 QListView{\n"
                                      "font-size: 12px;\n"
                                      "border: 1px solid rgba(0,0,0,10%);\n"
                                      "padding: 5px;\n"
                                      "background-color:#fff;\n"
                                      "outline:0px;\n"
                                      "}\n"
                                      "#comboBox_3 QListView::item{\n"
                                      "padding-left: 10px;\n"
                                      "background-color: #fff\n"
                                      "}\n"
                                      "#comboBox_3 QListView::item:selected{\n"
                                      "background-color:#FF00E5;\n"
                                      "}\n"
                                      "\n"
                                      "")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 71, 19))
        self.label_2.setStyleSheet("font-size: 16px;\n"
                                   "font: 75 16pt \"Arial\";\n"
                                   "color: #fff;")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 262, 34))
        self.comboBox.setStyleSheet("#comboBox{\n"
                                    "color: #fff;\n"
                                    "font: 75 10pt \"Arial\";\n"
                                    "border-radius: 8px;\n"
                                    "border: 1px solid #FFF;\n"
                                    "background: rgba(217, 217, 217, 0.10);\n"
                                    "}\n"
                                    "#comboBox::drop-down{\n"
                                    "border: 0px;\n"
                                    "}\n"
                                    "#comboBox::down-arrow{\n"
                                    "image: url(./newPrefix/arrow_drop_down_icon_206159.svg);\n"
                                    "margin-right: 15px;\n"
                                    "}\n"
                                    "#comboBox::one{\n"
                                    "border: 1px solid #FFF;\n"
                                    "}\n"
                                    "#comboBox QListView{\n"
                                    "font-size: 14px;\n"
                                    "border: 1px solid rgba(0,0,0,10%);\n"
                                    "padding: 5px;\n"
                                    "\n"
                                    "сolor:#fff;\n"
                                    "background-color:#fff;\n"
                                    "outline:0px;\n"
                                    "}\n"
                                    "#comboBox QListView::item{\n"
                                    "padding-left: 10px;\n"
                                    "background-color: #fff\n"
                                    "}\n"
                                    "#comboBox QListView::item:selected{\n"
                                    "background-color:#FF00E5;\n"
                                    "}\n"
                                    "\n"
                                    "")
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 40, 262, 34))
        self.comboBox_2.setStyleSheet("#comboBox_2{\n"
                                      "font: 75 10pt \"Arial\";\n"
                                      "color: #fff;\n"
                                      "border-radius: 8px;\n"
                                      "border: 1px solid #FFF;\n"
                                      "background: rgba(217, 217, 217, 0.10);\n"
                                      "}\n"
                                      "#comboBox_2::drop-down{\n"
                                      "border: 0px;\n"
                                      "}\n"
                                      "#comboBox_2::down-arrow{\n"
                                      "image: url(./newPrefix/arrow_drop_down_icon_206159.svg);\n"
                                      "margin-right: 15px;\n"
                                      "}\n"
                                      "#comboBox_2::one{\n"
                                      "border: 1px solid #FFF;\n"
                                      "}\n"
                                      "#comboBox_2 QListView{\n"
                                      "font-size: 12px;\n"
                                      "border: 1px solid rgba(0,0,0,10%);\n"
                                      "padding: 5px;\n"
                                      "background-color:#fff;\n"
                                      "outline:0px;\n"
                                      "}\n"
                                      "#comboBox_2 QListView::item{\n"
                                      "padding-left: 10px;\n"
                                      "background-color: #fff\n"
                                      "}\n"
                                      "#comboBox_2 QListView::item:selected{\n"
                                      "background-color:#FF00E5;\n"
                                      "}\n"
                                      "\n"
                                      "")
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 120, 481, 171))
        self.label_6.setStyleSheet("image:url(./newPrefix/world-map-pn2g.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 370, 313, 34))
        self.pushButton.setStyleSheet("font-size: 14px;\n"
                                      "border-radius: 8px;\n"
                                      "border: 1px solid #FFF;\n"
                                      "background: rgba(217, 217, 217, 0.10);\n"
                                      "box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);\n"
                                      "color: #fff;")
        # self.pushButton.setStyleSheet("box-shadow: 0px 4px 4px rgba(0, 0, 0, 25);")#https://qaa-engineer.ru/est-li-kakaya-nibud-alternativa-svojstvu-css-box-shadow-v-pyqt5/
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 19))
        self.label.setStyleSheet("font-size: 16px;\n"
                                 "color: #fff;\n"
                                 "font: 75 16pt \"Arial\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        dict_combo = GetDate().first_config("monthly_and_annual_precipitation_amounts.csv")
        mas_country = list(dict_combo.keys())
        list_country = filter(None, mas_country)
        list_country = [s for s in list_country if s]
        # print(list_country[0])
        self.comboBox.addItems(list_country)
        self.comboBox.currentIndexChanged.connect(lambda: self.update_cb2_cb3(dict_combo))
        self.comboBox_2.currentIndexChanged.connect(lambda: self.update_cb3(dict_combo))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.action.triggered.connect(self.new_window_select_file)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Построить график"))
        self.pushButton.clicked.connect(self.open_window)

        # self.comboBox_2.addItems(mas_region)
        # self.comboBox_3.addItems(mas_station)

        self.label.setText(_translate("MainWindow", "Country"))
        self.label_2.setText(_translate("MainWindow", "Region"))
        self.label_3.setText(_translate("MainWindow", "Station"))

        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Выбор файлов"))

    def open_window(self):
        counry_select = self.comboBox.currentText()
        region_select = self.comboBox_2.currentText()
        station_select = self.comboBox_3.currentText()


        # проверка на пустоту
        if (station_select == "" or region_select == "" or station_select == ""):
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Поля station, region and country должны быть заполнены")
            error.setIcon(QMessageBox.Critical)
            error.exec_()
            QCoreApplication.exit(0)
        else:
            global new_window
            new_window = NewWindow(counry_select, region_select, station_select)
            new_window.show()

    def new_window_select_file(self):
        global widget
        self.widget = QWidget()
        # global new_window_select_file_
        self.ui = Ui_widget_select_files()
        self.ui.setupUi(self.widget)
        self.widget.show()


class NewWindow(QtWidgets.QMainWindow):  # QDialog
    def read_conf_(self, counry_select, region_select, station_select):
        year_mas = []
        sr_zn = []
        with open("monthly_and_annual_precipitation_amounts.csv", encoding='utf-8') as r_file:
            # Создаем объект reader, указываем символ-разделитель ","
            file_reader = csv.reader(r_file, delimiter=",")
            # Счетчик для подсчета количества строк и вывода заголовков столбцов
            count = 0
            # print("run func")
            # Считывание данных из CSV файла
            for row in file_reader:
                if count != 0:
                    if ((row[config.country] == counry_select) and (row[config.region] == region_select) and (
                            row[config.station] == station_select)):
                        if ((row[config.position_za_year] != "?") and (row[config.position_za_year] != "@") and (
                                float(row[config.position_za_year]) != -999.0) and (float(row[config.position_za_year]) != 999.0)):
                            year_mas.append(float(row[config.position_za_year]))
                            sr_zn.append(float(row[0]))
                count += 1
        return year_mas, sr_zn

    def __init__(self, counry_select, region_select, station_select):

        super().__init__()

        # global counry_select
        # print(counry_select)

        # super(NewWindow, self).__init__(*args, **kwargs)

        self.graphWidget = pg.PlotWidget()
        self.setCentralWidget(self.graphWidget)
        self.resize(1740, 900)

        # hour = [2010,2012,2013,2014,2015,2016,2017,2018,2019,2024]
        # temperature = [1103,860,929,1048,2015,2016,2017,2018,2019,2024]
        year_mas, sr_zn = self.read_conf_(counry_select, region_select, station_select)
        # print(year_mas)
        # print(sr_zn)
        # print(len(year_mas))
        # print(len(sr_zn))
        # plot data: x, y values
        pen = pg.mkPen(color=(255, 0, 0))
        # z = np.polyfit (sr_zn, year_mas, 2 )
        # p = np.poly1d (z)
        # self.graphWidget.plot(sr_zn,year_mas)
        self.graphWidget.plot(sr_zn, year_mas, pen=pen)
        # self.setWindowTitle('Новое окно')

        # Добавляем виджеты на окно
        # ...



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
